version: '3'

services:
  web:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEBUG=True # for development
    ports:
      - "80:80"
    volumes:
      - .:/home/app/web

    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=img_API
    env_file:
      - .env
